/// Flutter icons Micons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Micons
///      fonts:
///       - asset: fonts/Micons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Micons {
  Micons._();

  static const _kFontFam = 'Micons';
  static const String? _kFontPkg = null;

  static const IconData StoreIcon = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData StandIcon = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
